version: '3.8'

services:
  db:
    image: mysql
    container_name: pencaDB
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
